### ISSUE TITLE
forgejo support?

### ISSUE THREAD

**Issue by ripienaar** [h0tw1r3/puppet-gitea#2]
Any chance you can make it configurable enough that we can install [forgejo](https://codeberg.org/forgejo/forgejo) instead of gitea? For the moment it is a drop in replacement - even goes to the same binary path.  We retty much just need to be able to specify the custom archive location.  I think.

**Comment by h0tw1r3** [comment]
I'll look into making the auto-upgrade gitea code optional if a specific download url is specified.

**Comment by ripienaar** [comment]
Cool - they seem to move a bit quicker on security releases etc.  

https://forgejo.org/2024-02-release-v1-21-6-0/ :(

**Comment by h0tw1r3** [comment]
Addressed in #5

**Comment by ripienaar** [comment]
Amazing thank you
